version: '3.3'

networks:
  default:
    external:
      name: research-coder

services:

  rc-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASS: secret
      MYSQL_DB: staypoints
    ports:
      - 8080:80

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: staypoints